[tool.black]
line-length = 100
exclude = '''
(
   .venv
   |.mypy_cache 
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100

[tool.mypy]
python_version = "3.10"
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true

# equivalent to --strict option
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true 
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

[tool.poe.tasks]
lint = "flake8 src"
type = "mypy src"
format = "black src"
test = "python -m unittest discover -v tests"
test-coverage = "coverage run --source '.'  -m unittest discover -v tests"
test-module = "python -m unittest -v"
app = "streamlit run app.py"
data = "python src/data_generator.py"

[tool.coverage.run]
omit = ["tests/*", ".venv/*"]
